import { Achievement, Upgrade } from "./game-types";

export const initialUpgrades: Upgrade[] = [
  {
    id: "cursor",
    name: "Cursor Upgrade",
    description: "Click power +1",
    baseCost: 10,
    multiplier: 1.2,
    clickIncrement: 1,
    purchased: 0,
    unlocked: true,
  },
  {
    id: "double-click",
    name: "Double Click",
    description: "Double your click power",
    baseCost: 100,
    multiplier: 1.5,
    clickIncrement: 0,
    purchased: 0,
    maxPurchases: 1,
    prerequisites: ["cursor"],
    unlocked: false,
  },
  {
    id: "auto-clicker",
    name: "Auto Clicker",
    description: "Clicks automatically once per second",
    baseCost: 250,
    multiplier: 1.8,
    clickIncrement: 1,
    purchased: 0,
    prerequisites: ["cursor"],
    unlocked: false,
  },
  {
    id: "mega-cursor",
    name: "Mega Cursor",
    description: "Click power +5",
    baseCost: 500,
    multiplier: 2,
    clickIncrement: 5,
    purchased: 0,
    prerequisites: ["double-click"],
    unlocked: false,
  },
  {
    id: "hyper-click",
    name: "Hyper Click",
    description: "Click power +10",
    baseCost: 1000,
    multiplier: 2.5,
    clickIncrement: 10,
    purchased: 0,
    prerequisites: ["mega-cursor"],
    unlocked: false,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: "first-click",
    name: "First Click",
    description: "Click for the first time",
    requirement: {
      type: "clicks",
      value: 1,
    },
    unlocked: false,
    icon: "🖱️",
  },
  {
    id: "getting-started",
    name: "Getting Started",
    description: "Reach 100 clicks",
    requirement: {
      type: "clicks",
      value: 100,
    },
    unlocked: false,
    icon: "🚀",
  },
  {
    id: "click-master",
    name: "Click Master",
    description: "Reach 1,000 clicks",
    requirement: {
      type: "clicks",
      value: 1000,
    },
    unlocked: false,
    icon: "🎯",
  },
  {
    id: "click-grandmaster",
    name: "Click Grandmaster",
    description: "Reach 10,000 clicks",
    requirement: {
      type: "clicks",
      value: 10000,
    },
    unlocked: false,
    icon: "👑",
  },
  {
    id: "click-legend",
    name: "Click Legend",
    description: "Reach 100,000 clicks",
    requirement: {
      type: "clicks",
      value: 100000,
    },
    unlocked: false,
    icon: "🔥",
  },
  {
    id: "first-upgrade",
    name: "First Upgrade",
    description: "Purchase your first upgrade",
    requirement: {
      type: "upgrades",
      value: 1,
      upgradeId: "cursor",
    },
    unlocked: false,
    icon: "⬆️",
  },
  {
    id: "double-trouble",
    name: "Double Trouble",
    description: "Purchase the Double Click upgrade",
    requirement: {
      type: "upgrades",
      value: 1,
      upgradeId: "double-click",
    },
    unlocked: false,
    icon: "✌️",
  },
  {
    id: "auto-pilot",
    name: "Auto Pilot",
    description: "Purchase the Auto Clicker",
    requirement: {
      type: "upgrades",
      value: 1,
      upgradeId: "auto-clicker",
    },
    unlocked: false,
    icon: "⚙️",
  },
  {
    id: "mega-power",
    name: "Mega Power",
    description: "Purchase the Mega Cursor upgrade",
    requirement: {
      type: "upgrades",
      value: 1,
      upgradeId: "mega-cursor",
    },
    unlocked: false,
    icon: "💪",
  },
  {
    id: "hyper-speed",
    name: "Hyper Speed",
    description: "Purchase the Hyper Click upgrade",
    requirement: {
      type: "upgrades",
      value: 1,
      upgradeId: "hyper-click",
    },
    unlocked: false,
    icon: "⚡",
  },
  {
    id: "upgrade-collector",
    name: "Upgrade Collector",
    description: "Purchase at least 10 upgrades in total",
    requirement: {
      type: "upgrades",
      value: 10,
    },
    unlocked: false,
    icon: "🧰",
  },
  {
    id: "upgrade-addict",
    name: "Upgrade Addict",
    description: "Purchase at least 25 upgrades in total",
    requirement: {
      type: "upgrades",
      value: 25,
    },
    unlocked: false,
    icon: "🔧",
  },
  {
    id: "power-user",
    name: "Power User",
    description: "Reach 100 click power",
    requirement: {
      type: "score",
      value: 100,
    },
    unlocked: false,
    icon: "💪",
  },
  {
    id: "wealthy",
    name: "Wealthy",
    description: "Reach 1,000 points",
    requirement: {
      type: "score",
      value: 1000,
    },
    unlocked: false,
    icon: "💰",
  },
  {
    id: "millionaire",
    name: "Millionaire",
    description: "Reach 1,000,000 points",
    requirement: {
      type: "score",
      value: 1000000,
    },
    unlocked: false,
    icon: "💎",
  },
  {
    id: "billionaire",
    name: "Billionaire",
    description: "Reach 1,000,000,000 points",
    requirement: {
      type: "score",
      value: 1000000000,
    },
    unlocked: false,
    icon: "🏆",
  },
  {
    id: "quick-fingers",
    name: "Quick Fingers",
    description: "Click 50 times in 10 seconds",
    requirement: {
      type: "clicks",
      value: 50,
    },
    unlocked: false,
    icon: "⚡",
  },
  {
    id: "dedicated-clicker",
    name: "Dedicated Clicker",
    description: "Reach 500,000 clicks",
    requirement: {
      type: "clicks",
      value: 500000,
    },
    unlocked: false,
    icon: "🔄",
  },
  {
    id: "click-addiction",
    name: "Click Addiction",
    description: "Reach 1,000,000 clicks",
    requirement: {
      type: "clicks",
      value: 1000000,
    },
    unlocked: false,
    icon: "🧠",
  },
  {
    id: "upgrade-master",
    name: "Upgrade Master",
    description: "Purchase at least 50 upgrades in total",
    requirement: {
      type: "upgrades",
      value: 50,
    },
    unlocked: false,
    icon: "🔨",
  },
  {
    id: "upgrade-maximizer",
    name: "Upgrade Maximizer",
    description: "Purchase at least 100 upgrades in total",
    requirement: {
      type: "upgrades",
      value: 100,
    },
    unlocked: false,
    icon: "⚒️",
  },
  {
    id: "points-hoarder",
    name: "Points Hoarder",
    description: "Reach 10,000,000 points",
    requirement: {
      type: "score",
      value: 10000000,
    },
    unlocked: false,
    icon: "💸",
  },
  {
    id: "trillionaire",
    name: "Trillionaire",
    description: "Reach 1,000,000,000,000 points",
    requirement: {
      type: "score",
      value: 1000000000000,
    },
    unlocked: false,
    icon: "🌟",
  }
]; 